/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import negocio.Conjunto;

/**
 *
 * @author 59178
 */
public class FConjunto extends javax.swing.JFrame {
        Conjunto A;
        Conjunto B;
        Conjunto C;
    /**
     * Creates new form FConjunto
     */
    public FConjunto() {
        initComponents();
        setLocationRelativeTo(null);//Al ejecutar el form
        //coloca la ventana al centro de la pantalla(null)
        A=new Conjunto();
        B=new Conjunto();
        C=new Conjunto();
        //para no poder editar el campo "text area"
        jta_A.setEditable(false);
        jta_B.setEditable(false);
        jta_res.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_A = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta_B = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jta_res = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbx_insertar = new javax.swing.JComboBox<>();
        jcbx_eliminar = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jcbx_res = new javax.swing.JComboBox<>();
        jBttn_insert = new javax.swing.JButton();
        jbttn_calc = new javax.swing.JButton();
        jbttn_elim = new javax.swing.JButton();
        jtf_insert = new javax.swing.JTextField();
        jtf_elim = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 153, 51));

        jta_A.setColumns(20);
        jta_A.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jta_A.setRows(5);
        jScrollPane1.setViewportView(jta_A);

        jta_B.setColumns(20);
        jta_B.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jta_B.setRows(5);
        jScrollPane2.setViewportView(jta_B);

        jta_res.setColumns(20);
        jta_res.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jta_res.setRows(5);
        jScrollPane3.setViewportView(jta_res);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Conjunto A:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Conjunto B:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Resultado:");

        jLabel4.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        jLabel4.setText("TDA CONJUNTO");

        jcbx_insertar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jcbx_insertar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Insertar en A", "Insertar en B" }));
        jcbx_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbx_insertarActionPerformed(evt);
            }
        });

        jcbx_eliminar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jcbx_eliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eliminar en A", "Eliminar en B" }));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Operaciones:");

        jcbx_res.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jcbx_res.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Union", "Interseccion", "Subconjunto", " " }));
        jcbx_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbx_resActionPerformed(evt);
            }
        });

        jBttn_insert.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBttn_insert.setText("Realizar");
        jBttn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttn_insertActionPerformed(evt);
            }
        });

        jbttn_calc.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbttn_calc.setText("Calcular");
        jbttn_calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn_calcActionPerformed(evt);
            }
        });

        jbttn_elim.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbttn_elim.setText("Realizar");
        jbttn_elim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttn_elimActionPerformed(evt);
            }
        });

        jtf_insert.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jtf_elim.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel6))
                            .addComponent(jtf_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jcbx_eliminar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcbx_insertar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jtf_elim, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbx_res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBttn_insert)
                                    .addComponent(jbttn_elim)
                                    .addComponent(jbttn_calc))))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcbx_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBttn_insert))
                                .addGap(2, 2, 2)
                                .addComponent(jtf_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcbx_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbttn_elim)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jtf_elim, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbx_res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbttn_calc))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 740, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbx_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbx_insertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbx_insertarActionPerformed

    private void jcbx_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbx_resActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbx_resActionPerformed

    private void jBttn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttn_insertActionPerformed
        // TODO add your handling code here:
        int usuario=jcbx_insertar.getSelectedIndex();
        if(jcbx_insertar.getItemAt(usuario)=="Insertar en A"){
            A.insertar(Integer.parseInt(jtf_insert.getText()));
            jta_A.setText(A.toString());
        }else{
            B.insertar(Integer.parseInt(jtf_insert.getText()));
            jta_B.setText(B.toString()); 
        }
        //Luego de insertar se limpia el campo de texto
       jtf_insert.setText("");
        
    }//GEN-LAST:event_jBttn_insertActionPerformed

    private void jbttn_elimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn_elimActionPerformed
        // TODO add your handling code here:
        int usuario=jcbx_eliminar.getSelectedIndex();//Devuelve la
        //posición del item seleccionado por el usuario
        if(jcbx_eliminar.getItemAt(usuario)=="Eliminar en A"){
            A.eliminar(Integer.parseInt(jtf_elim.getText()));
            jta_A.setText(A.toString());
        }else{
            B.eliminar(Integer.parseInt(jtf_elim.getText()));
            jta_B.setText(B.toString()); 
        }
        jtf_elim.setText("");
    }//GEN-LAST:event_jbttn_elimActionPerformed

    private void jbttn_calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttn_calcActionPerformed
        // TODO add your handling code here:
        int usuario=jcbx_res.getSelectedIndex();
        if(jcbx_res.getItemAt(usuario)=="Union"){
            C=new Conjunto();
            C.union(A, B);
            jta_res.setText(C.toString());
        }else{
            if(jcbx_res.getItemAt(usuario)=="Interseccion"){
                C=new Conjunto();
                C.interseccion(A, B);
                jta_res.setText(C.toString());
            }else{//Verificar subconjuntos
                C=new Conjunto();  
                if(C.subconjunto(A, B)&& C.subconjunto(B, A)){
                    jta_res.setText("A es subconjunto de B y B es subconjunto de A");
                }else{
                if(C.subconjunto(A, B)){
                   jta_res.setText("A es subconjunto de B"); 
                }else{
                    if(C.subconjunto(B, A)){
                     jta_res.setText("B es subconjunto de A");   
                    }else{
                     jta_res.setText("No hay subconjuntos");  
                    }
                }
                }
            }
        }
        
    }//GEN-LAST:event_jbttn_calcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FConjunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FConjunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FConjunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FConjunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FConjunto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttn_insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbttn_calc;
    private javax.swing.JButton jbttn_elim;
    private javax.swing.JComboBox<String> jcbx_eliminar;
    private javax.swing.JComboBox<String> jcbx_insertar;
    private javax.swing.JComboBox<String> jcbx_res;
    private javax.swing.JTextArea jta_A;
    private javax.swing.JTextArea jta_B;
    private javax.swing.JTextArea jta_res;
    private javax.swing.JTextField jtf_elim;
    private javax.swing.JTextField jtf_insert;
    // End of variables declaration//GEN-END:variables
}
