/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JOptionPane;
import negocio.FichaCovid;

/**
 *
 * @author 59178
 */
public class FCovid19 extends javax.swing.JFrame {
          int nro;
          FichaCovid A;
    /**
     * Creates new form FCovid19
     */
    public FCovid19() {
        initComponents();
        setLocationRelativeTo(null);
        A=new FichaCovid(15);
        nro=1;
        jtf_nro.setText(String.valueOf(nro));
      
        jtf_nro.setEnabled(false);
        jtf_mostrar.setEnabled(false);
        jbtt_mostrar.setEnabled(false);
        
        jta_ficha.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo = new javax.swing.ButtonGroup();
        gusto = new javax.swing.ButtonGroup();
        olfato = new javax.swing.ButtonGroup();
        muscular = new javax.swing.ButtonGroup();
        diarrea = new javax.swing.ButtonGroup();
        respiracion = new javax.swing.ButtonGroup();
        cabeza = new javax.swing.ButtonGroup();
        garganta = new javax.swing.ButtonGroup();
        tos = new javax.swing.ButtonGroup();
        fiebre = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jrb_olfatoSI = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jrb_muscularSI = new javax.swing.JRadioButton();
        jrb_diarreaSI = new javax.swing.JRadioButton();
        jrb_respiracionSI = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jrb_cabezaSI = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jrb_tosSI = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jrb_gustoSI = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jrb_gargantaSI = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jrb_fiebreSI = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jrb_sexoM = new javax.swing.JRadioButton();
        jrb_sexoF = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jtf_mostrar = new javax.swing.JTextField();
        jbtt_mostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_ficha = new javax.swing.JTextArea();
        jtf_nombre = new javax.swing.JTextField();
        jtf_edad = new javax.swing.JTextField();
        jtf_peso = new javax.swing.JTextField();
        jtf_dia = new javax.swing.JTextField();
        jtf_mes = new javax.swing.JTextField();
        jtf_año = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtf_nro = new javax.swing.JTextField();
        jbtt_insertar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("N°");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Formulario de análisis Covid");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Edad:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Sexo:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Peso:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Sintomas");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Fecha:d-m-aaaa");

        olfato.add(jrb_olfatoSI);
        jrb_olfatoSI.setSelected(true);
        jrb_olfatoSI.setText("SI");

        muscular.add(jRadioButton2);
        jRadioButton2.setText("NO");

        diarrea.add(jRadioButton3);
        jRadioButton3.setText("NO");

        olfato.add(jRadioButton4);
        jRadioButton4.setText("NO");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        muscular.add(jrb_muscularSI);
        jrb_muscularSI.setSelected(true);
        jrb_muscularSI.setText("SI");

        diarrea.add(jrb_diarreaSI);
        jrb_diarreaSI.setSelected(true);
        jrb_diarreaSI.setText("SI");

        respiracion.add(jrb_respiracionSI);
        jrb_respiracionSI.setSelected(true);
        jrb_respiracionSI.setText("SI");

        respiracion.add(jRadioButton8);
        jRadioButton8.setText("NO");

        cabeza.add(jrb_cabezaSI);
        jrb_cabezaSI.setSelected(true);
        jrb_cabezaSI.setText("SI");

        cabeza.add(jRadioButton10);
        jRadioButton10.setText("NO");

        tos.add(jrb_tosSI);
        jrb_tosSI.setSelected(true);
        jrb_tosSI.setText("SI");
        jrb_tosSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_tosSIActionPerformed(evt);
            }
        });

        tos.add(jRadioButton12);
        jRadioButton12.setText("NO");

        gusto.add(jrb_gustoSI);
        jrb_gustoSI.setSelected(true);
        jrb_gustoSI.setText("SI");

        gusto.add(jRadioButton14);
        jRadioButton14.setText("NO");

        garganta.add(jrb_gargantaSI);
        jrb_gargantaSI.setSelected(true);
        jrb_gargantaSI.setText("SI");

        garganta.add(jRadioButton16);
        jRadioButton16.setText("NO");

        fiebre.add(jrb_fiebreSI);
        jrb_fiebreSI.setSelected(true);
        jrb_fiebreSI.setText("SI");
        jrb_fiebreSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_fiebreSIActionPerformed(evt);
            }
        });

        fiebre.add(jRadioButton18);
        jRadioButton18.setText("NO");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Dolor de cabeza:");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Perdida del olfato:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("Dolor Muscular:");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("Diarrea:");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setText("Falta de Respiracion:");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setText("Fiebre:");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("Perdida del gusto:");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText("Dolor de garganta:");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setText("Tos:");

        sexo.add(jrb_sexoM);
        jrb_sexoM.setSelected(true);
        jrb_sexoM.setText("M");

        sexo.add(jrb_sexoF);
        jrb_sexoF.setText("F");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setText("FICHA");

        jtf_mostrar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jbtt_mostrar.setText("MOSTRAR");
        jbtt_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtt_mostrarActionPerformed(evt);
            }
        });

        jta_ficha.setColumns(20);
        jta_ficha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jta_ficha.setRows(5);
        jScrollPane1.setViewportView(jta_ficha);

        jtf_nombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jtf_edad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jtf_peso.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtf_peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_pesoActionPerformed(evt);
            }
        });

        jtf_dia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtf_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_diaActionPerformed(evt);
            }
        });

        jtf_mes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jtf_año.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel19.setText("Dia");

        jLabel20.setText("Mes");

        jLabel21.setText("Año");

        jtf_nro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jbtt_insertar.setText("INSERTAR");
        jbtt_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtt_insertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel20)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(44, 44, 44)
                        .addComponent(jtf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jtf_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_mes))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_nro, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jrb_sexoM)
                                .addGap(18, 18, 18)
                                .addComponent(jrb_sexoF))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel19))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(35, 35, 35)
                                .addComponent(jtf_peso)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel21))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jtf_año, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jrb_fiebreSI)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton18)))
                .addGap(191, 191, 191)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jrb_olfatoSI))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(43, 43, 43)
                                        .addComponent(jrb_gustoSI))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel16))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrb_muscularSI)
                                    .addComponent(jrb_diarreaSI)
                                    .addComponent(jrb_respiracionSI)
                                    .addComponent(jrb_cabezaSI)
                                    .addComponent(jrb_gargantaSI)
                                    .addComponent(jrb_tosSI))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jbtt_insertar))
                            .addComponent(jRadioButton16))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtt_mostrar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(301, 301, 301)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jrb_cabezaSI)
                                            .addComponent(jLabel9)
                                            .addComponent(jRadioButton10)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(jLabel10))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jrb_gustoSI)
                                                .addComponent(jLabel15)
                                                .addComponent(jRadioButton14))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jRadioButton4)
                                                    .addComponent(jrb_olfatoSI))))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jRadioButton2)
                                            .addComponent(jLabel11)
                                            .addComponent(jrb_muscularSI))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jrb_diarreaSI)
                                            .addComponent(jRadioButton3)
                                            .addComponent(jLabel12))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jrb_respiracionSI)
                                            .addComponent(jRadioButton8)
                                            .addComponent(jLabel13)
                                            .addComponent(jbtt_insertar))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jtf_nro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jtf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jrb_sexoF)
                                    .addComponent(jrb_sexoM))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jtf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel20)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb_gargantaSI, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(jtf_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtf_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtf_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb_tosSI, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton12)
                                .addComponent(jLabel17)
                                .addComponent(jLabel14)
                                .addComponent(jrb_fiebreSI)
                                .addComponent(jRadioButton18)))
                        .addGap(52, 52, 52))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jtf_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtt_mostrar)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1230, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_tosSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_tosSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_tosSIActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jrb_fiebreSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_fiebreSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_fiebreSIActionPerformed

    private void jtf_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_diaActionPerformed

    private void jbtt_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtt_insertarActionPerformed
        // TODO add your handling code here:
        int sex;
         if(jrb_sexoM.isSelected()){
             sex=0;
             
         }else{
             sex=1;
         }
         int edad=Integer.parseInt(jtf_edad.getText());
         System.out.println(edad);
         int año=Integer.parseInt(jtf_año.getText());
         int mes=Integer.parseInt(jtf_mes.getText());
         int dia=Integer.parseInt(jtf_dia.getText());
         String peso=jtf_peso.getText();
         int kg=Integer.parseInt(peso.substring(0,peso.indexOf(".")));
        // System.out.println(kg);
         int gr=Integer.parseInt(peso.substring(peso.indexOf(".")+1));
         //System.out.println(gr);
       //PRIMER INSERTADO
        A.insertar(jtf_nombre.getText(),edad,año,mes,dia,sex,kg,gr);
        int gusto;
        if(jrb_gustoSI.isSelected()){
             gusto=1;
             
         }else{
             gusto=0;
         }
         int olfato;
        if(jrb_olfatoSI.isSelected()){
             olfato=1;
             
         }else{
             olfato=0;
         }
         int muscular;
        if(jrb_muscularSI.isSelected()){
             muscular=1;
             
         }else{
             muscular=0;
         }
         int diarrea;
        if(jrb_diarreaSI.isSelected()){
             diarrea=1;
             
         }else{
             diarrea=0;
         }
          int respiracion;
        if(jrb_respiracionSI.isSelected()){
             respiracion=1;
             
         }else{
             respiracion=0;
         }
           int cabeza;
        if(jrb_cabezaSI.isSelected()){
             cabeza=1;
             
         }else{
             cabeza=0;
         }
               int garganta;
        if(jrb_gargantaSI.isSelected()){
             garganta=1;
             
         }else{
             garganta=0;
         }       
                  int tos;
        if(jrb_tosSI.isSelected()){
             tos=1;
             
         }else{
             tos=0;
         }      
           int fiebre;
        if(jrb_fiebreSI.isSelected()){
             fiebre=1;
             
         }else{
             fiebre=0;
         }  
      //2DO INSERTADO
      A.insertarSintomas(gusto, olfato, muscular, diarrea, respiracion, cabeza, garganta, tos, fiebre);
      jtf_mostrar.setEnabled(true);
      jbtt_mostrar.setEnabled(true);
      nro++;
      jtf_nro.setText(String.valueOf(nro));
      JOptionPane.showMessageDialog(rootPane,"Guardado exitoso!!");
      jtf_nombre.setText("");
      jtf_edad.setText("");
      jtf_dia.setText("");
      jtf_mes.setText("");
      jtf_año.setText("");
      jtf_peso.setText("");
      
      jrb_gustoSI.setSelected(true);
      jrb_olfatoSI.setSelected(true);
      jrb_muscularSI.setSelected(true);
      jrb_diarreaSI.setSelected(true);
      jrb_respiracionSI.setSelected(true);
      jrb_cabezaSI.setSelected(true);
      jrb_gargantaSI.setSelected(true);
      jrb_tosSI.setSelected(true);
      jrb_fiebreSI.setSelected(true);
    }//GEN-LAST:event_jbtt_insertarActionPerformed

    private void jtf_pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_pesoActionPerformed

    private void jbtt_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtt_mostrarActionPerformed
        // TODO add your handling code here:
        int pos=Integer.parseInt(jtf_mostrar.getText());
        jta_ficha.setText(A.MostrarFichaCovid(pos));
    }//GEN-LAST:event_jbtt_mostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FCovid19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FCovid19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FCovid19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FCovid19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FCovid19().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup cabeza;
    private javax.swing.ButtonGroup diarrea;
    private javax.swing.ButtonGroup fiebre;
    private javax.swing.ButtonGroup garganta;
    private javax.swing.ButtonGroup gusto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtt_insertar;
    private javax.swing.JButton jbtt_mostrar;
    private javax.swing.JRadioButton jrb_cabezaSI;
    private javax.swing.JRadioButton jrb_diarreaSI;
    private javax.swing.JRadioButton jrb_fiebreSI;
    private javax.swing.JRadioButton jrb_gargantaSI;
    private javax.swing.JRadioButton jrb_gustoSI;
    private javax.swing.JRadioButton jrb_muscularSI;
    private javax.swing.JRadioButton jrb_olfatoSI;
    private javax.swing.JRadioButton jrb_respiracionSI;
    private javax.swing.JRadioButton jrb_sexoF;
    private javax.swing.JRadioButton jrb_sexoM;
    private javax.swing.JRadioButton jrb_tosSI;
    private javax.swing.JTextArea jta_ficha;
    private javax.swing.JTextField jtf_año;
    private javax.swing.JTextField jtf_dia;
    private javax.swing.JTextField jtf_edad;
    private javax.swing.JTextField jtf_mes;
    private javax.swing.JTextField jtf_mostrar;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_nro;
    private javax.swing.JTextField jtf_peso;
    private javax.swing.ButtonGroup muscular;
    private javax.swing.ButtonGroup olfato;
    private javax.swing.ButtonGroup respiracion;
    private javax.swing.ButtonGroup sexo;
    private javax.swing.ButtonGroup tos;
    // End of variables declaration//GEN-END:variables
}
