/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocio.Lista;
import Negocio.Nodo;
import Negocio.Lista2;
import Negocio.Nodo2;
/**
 *
 * @author Usuario
 */
public class Formulario extends javax.swing.JFrame {

    Lista L = new Lista();
    Lista2 Q = new Lista2();
    public Formulario() {
        initComponents();
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Vacio", "Insertar", "Eliminar", "Sacar", "Buscar", "BuscarR", "Invertir", "InvertirR", "Inver2a2", "Inver3a3", "Inver1yn", "Inver2a2_1", "Domino" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("ENTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                .addGap(83, 83, 83)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int index = jList1.getSelectedIndex();
        switch (index){
            case 0:
                if (L.Vacia()==true){
                    jLabel2.setText("SI ESTA VACIA");
                }else{
                    jLabel2.setText("NO ESTA VACIA");
                }
                mostrar();
                break;
            case 1:
                if (!jTextField1.getText().isEmpty()){
                    L.Insertar(Integer.valueOf(jTextField1.getText()));
                    mostrar();
                    jLabel2.setText("");
                }
                break;
            case 2:
                if (!jTextField1.getText().isEmpty()){
                    L.Eliminar(Integer.valueOf(jTextField1.getText()));
                    mostrar();
                    jLabel2.setText("");
                }
                break;
            case 3:
                if (!jTextField1.getText().isEmpty()){
                    if(Integer.valueOf(jTextField1.getText())<=L.dim){
                        jLabel2.setText(String.valueOf(L.Sacar(Integer.valueOf(jTextField1.getText()))));
                        mostrar();
                    }
                }
                break;
            case 4:
                if (L.Buscar(Integer.valueOf(jTextField1.getText()))==true){
                    jLabel2.setText("SI SE ENCUENTRA");
                }else{
                    jLabel2.setText("NO SE ENCUENTRA");
                }
                break;
            case 5:
                if (L.BuscarR(Integer.valueOf(jTextField1.getText()))==true){
                    jLabel2.setText("SI SE ENCUENTRA");
                }else{
                    jLabel2.setText("NO SE ENCUENTRA");
                }
                break;
            case 6:
                L.Invertir();
                mostrar();
                break;
            case 7:
                L.InvertirR();
                mostrar();
                break;
            case 8:
                L.Inter2a2();
                mostrar();
                break;
            case 9:
                L.Inter3a3();
                mostrar();
                break;
            case 10:
                L.Inter1yn();
                mostrar();
                break;
            case 11:
                L.Inter2a2_1();
                mostrar();
                break;
                
            case 12:
                if(!jTextField1.getText().isEmpty()){
                    Q.Insertar(Integer.valueOf(jTextField1.getText()), Integer.valueOf(jTextField1.getText()));
                    mostrar1();
                    jLabel2.setText("");
                }
            break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void mostrar(){
        if(!L.Vacia()){
            jLabel1.setText("L->"+L.toString());
            jLabel3.setText(String.valueOf("Dim: "+L.dim));
        }else{
            jLabel1.setText("L==null");
            jLabel3.setText(String.valueOf("Dim=="+L.dim));
        }
    }
    public void mostrar1(){
        if(!Q.Vacia()){
            jLabel1.setText("L->"+Q.toString());
            jLabel3.setText(String.valueOf("Dim: "+Q.dim));
        }else{
            jLabel1.setText("L==null");
            jLabel3.setText(String.valueOf("Dim=="+Q.dim));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
