/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import negocio.fraccion;

/**
 *
 * @author 59178
 */
public class Ffraccion extends javax.swing.JFrame {
    
    fraccion A;
    fraccion B;
    fraccion C;
    boolean numA, denA, numB, denB;

    //constructor por defecto
    public Ffraccion() {
        initComponents();
        A = new fraccion();
        B = new fraccion();
        C = new fraccion();
        numA = denA = numB = denB = false;
        setLocationRelativeTo(null);//Al ejecutar el form
        //coloca la ventana al centro de la pantalla(null)
        this.jtf_numC.setVisible(false);
        this.jtf_denC.setVisible(false);
        this.jsptr_resultado.setVisible(false);
        this.jlbl_pos.setVisible(false);
        this.jlbl_neg.setVisible(false);
        this.jbtt_resultado.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jtf_denB = new javax.swing.JTextField();
        jbtt_resultado = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jsptr_resultado = new javax.swing.JSeparator();
        jtf_numA = new javax.swing.JTextField();
        jtf_numC = new javax.swing.JTextField();
        jtf_denA = new javax.swing.JTextField();
        jtf_denC = new javax.swing.JTextField();
        jcbx_operacion = new javax.swing.JComboBox<>();
        jcbx_signoB = new javax.swing.JComboBox<>();
        jtf_numB = new javax.swing.JTextField();
        jcbx_signoA = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jlbl_pos = new javax.swing.JLabel();
        jlbl_neg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PANEL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        jtf_denB.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtf_denB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_denBKeyReleased(evt);
            }
        });

        jbtt_resultado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbtt_resultado.setText("=");
        jbtt_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtt_resultadoActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jsptr_resultado.setForeground(new java.awt.Color(0, 0, 0));

        jtf_numA.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtf_numA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_numAKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_denAKeyReleased(evt);
            }
        });

        jtf_numC.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jtf_denA.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtf_denA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_numBKeyReleased(evt);
            }
        });

        jtf_denC.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jcbx_operacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jcbx_operacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SUMA", "RESTA", "MULTIPLICACION", "DIVISION" }));

        jcbx_signoB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jcbx_signoB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));

        jtf_numB.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jcbx_signoA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jcbx_signoA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("TDA FRACCION");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jlbl_pos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbl_pos.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_pos.setText("+");

        jlbl_neg.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbl_neg.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_neg.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jtf_numA, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jcbx_signoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jtf_denA, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbx_operacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jcbx_signoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_numB, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(jtf_denB)
                            .addComponent(jSeparator5))
                        .addGap(18, 18, 18)
                        .addComponent(jbtt_resultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbl_pos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jlbl_neg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jsptr_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 22, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_denC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_numC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jtf_numA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(16, 16, 16)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jtf_denA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jcbx_signoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jcbx_operacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jtf_numB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(8, 8, 8)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(8, 8, 8)
                                    .addComponent(jtf_denB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbtt_resultado)
                                        .addComponent(jlbl_pos)
                                        .addComponent(jlbl_neg))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtf_numC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jsptr_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_denC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jcbx_signoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 750, 390));

        jMenuBar1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem3.setText("jMenuItem3");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_numAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_numAKeyReleased
        // Al teclear el campo de texto numA
        numA = true;
        if (numA && denA && numB && denB) {
            this.jbtt_resultado.setEnabled(true);
        }
    }//GEN-LAST:event_jtf_numAKeyReleased

    private void jtf_denAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_denAKeyReleased
        // Al teclear el campo de texto denA
        //evt=evento
        denA = true;
        if (numA && denA && numB && denB) {
            this.jbtt_resultado.setEnabled(true);
        }
    }//GEN-LAST:event_jtf_denAKeyReleased

    private void jtf_numBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_numBKeyReleased
        // Al teclear el campo de texto numB
        //evt=evento
        numB = true;
        if (numA && denA && numB && denB) {
            this.jbtt_resultado.setEnabled(true);
        }
    }//GEN-LAST:event_jtf_numBKeyReleased

    private void jtf_denBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_denBKeyReleased
        // Al teclear el campo de texto numB
        //evt=evento
        denB = true;
        if (numA && denA && numB && denB) {
            this.jbtt_resultado.setEnabled(true);
        }
    }//GEN-LAST:event_jtf_denBKeyReleased

    private void jbtt_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtt_resultadoActionPerformed
        // Cargando el objeto A
        int nA = Integer.parseInt(this.jtf_numA.getText());
        int dA = Integer.parseInt(this.jtf_denA.getText());
        char signo = this.jcbx_signoA.getSelectedItem().toString().charAt(0);
        /*
        Funcionamiento del charAt(int index(indice))
           String prueba="Hola mundo";
          char caracter_indice=prueba.charAt(0);//H
         */
        if(dA!=0){
        A.setNum(nA);
        A.setDen(dA);
        A.setSigno(signo);}
        else{
           this.jTextArea1.setText("Error::El denominador no puede ser 0");
        }
        //Cargando el objeto B
        int nB = Integer.parseInt(this.jtf_numB.getText());
        int dB = Integer.parseInt(this.jtf_denB.getText());
        char signoB = this.jcbx_signoB.getSelectedItem().toString().charAt(0);
       if(dB!=0){
        B.setNum(nB);
        B.setDen(dB);
        B.setSigno(signoB);}
       else{
           this.jTextArea1.setText("Error::El denominador no puede ser 0");
       }
        //Realizando la operacion solicitada
        String op = this.jcbx_operacion.getSelectedItem().toString();
        switch (op) {
            case "SUMA":
                C.suma(A, B);
                break;
            case "RESTA":
                C.resta(A, B);
                break;
            case "MULTIPLICACION":
                C.multiplicar(A, B);
                break;
            case "DIVISION":
                C.dividir(A, B);
                break;
            
        }
        mostrar();

    }//GEN-LAST:event_jbtt_resultadoActionPerformed
    private void mostrar() {
        this.jtf_numC.setText(String.valueOf(C.getNum()));
        this.jtf_denC.setText(String.valueOf(C.getDen()));
        char signoC = C.getSigno();
        if (signoC == '+') {
            this.jlbl_pos.setVisible(true);
            this.jlbl_neg.setVisible(false);
        } else {
            this.jlbl_neg.setVisible(true);
            this.jlbl_pos.setVisible(false);
        }
        this.jtf_numC.setVisible(true);
        this.jtf_denC.setVisible(true);
        this.jsptr_resultado.setVisible(true);
    }    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ffraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ffraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ffraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ffraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ffraccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbtt_resultado;
    private javax.swing.JComboBox<String> jcbx_operacion;
    private javax.swing.JComboBox<String> jcbx_signoA;
    private javax.swing.JComboBox<String> jcbx_signoB;
    private javax.swing.JLabel jlbl_neg;
    private javax.swing.JLabel jlbl_pos;
    private javax.swing.JSeparator jsptr_resultado;
    private javax.swing.JTextField jtf_denA;
    private javax.swing.JTextField jtf_denB;
    private javax.swing.JTextField jtf_denC;
    private javax.swing.JTextField jtf_numA;
    private javax.swing.JTextField jtf_numB;
    private javax.swing.JTextField jtf_numC;
    // End of variables declaration//GEN-END:variables
}
